spring.application.name=carSearch_backend


gemini.api.key=${GEMINI_API_KEY:}
pexels.api.key=${PEXELS_API_KEY:}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
